/**
 * Fixtures del shim AVANZADO (S12, SLICES.md §S12, tabla "Avanzado" de
 * C-RUNNER en ARCHITECTURE.md). Cada fixture usa la superficie EXACTA de esa
 * tabla y, cuando el grounding avanzado trae un ejemplo literal, lo transcribe
 * verbatim (los oráculos son esos ejemplos, no una reinterpretación).
 *
 * Convenciones (iguales a `fixtures.ts` de S6):
 * - `studentCode` construye el grafo (lo que vería el alumno).
 * - `validationCode` usa EXCLUSIVAMENTE `course_harness`
 *   (`check`/`check_eq`/`check_raises`/`get_llm_calls`) — nunca `run_graph`
 *   (no existe, C-CONTENT "Reglas M3").
 * - `llmDoubles` sigue el shape de `LlmDouble` (C-CONTENT): sin `id` en
 *   `toolCalls` — el shim debe generarlos como `call_1`, `call_2`, …
 *   (C-RUNNER §tabla avanzada, fila `AIMessage.tool_calls`).
 */

import type { LlmDoubleLike } from "./helpers";

// ---------------------------------------------------------------------------
// 1) Checkpointing: InMemorySaver + thread_id + get_state/get_state_history
// ---------------------------------------------------------------------------

/** El estado del hilo sobrevive entre invokes; hilos distintos están
 *  aislados; `get_state` expone `.values`/`.next`. */
export const CHECKPOINT_PERSISTENCE_CHALLENGE = {
  id: "test-checkpoint-persistence",
  studentCode: [
    "import operator",
    "from typing import Annotated",
    "from typing_extensions import TypedDict",
    "from langgraph.checkpoint.memory import InMemorySaver",
    "from langgraph.graph import END, START, StateGraph",
    "",
    "class State(TypedDict):",
    "    count: Annotated[list, operator.add]",
    "",
    "def increment(state: State):",
    '    return {"count": [1]}',
    "",
    "graph = (",
    "    StateGraph(State)",
    '    .add_node("increment", increment)',
    '    .add_edge(START, "increment")',
    '    .add_edge("increment", END)',
    "    .compile(checkpointer=InMemorySaver())",
    ")",
  ].join("\n"),
  validationCode: [
    "from course_harness import check, check_eq",
    "",
    'config_a = {"configurable": {"thread_id": "thread-a"}}',
    'config_b = {"configurable": {"thread_id": "thread-b"}}',
    "",
    'r1 = graph.invoke({"count": []}, config_a)',
    'check_eq("thread_a_first", "primer invoke en thread-a", r1["count"], [1])',
    "",
    'r2 = graph.invoke({"count": []}, config_a)',
    'check_eq(',
    '    "thread_a_second",',
    '    "segundo invoke en thread-a acumula (el checkpoint persiste entre invokes)",',
    '    r2["count"],',
    '    [1, 1],',
    ")",
    "",
    'r3 = graph.invoke({"count": []}, config_b)',
    'check_eq(',
    '    "thread_b_isolated",',
    '    "thread-b arranca aislado: no ve el estado de thread-a",',
    '    r3["count"],',
    '    [1],',
    ")",
    "",
    "snapshot = graph.get_state(config_a)",
    'check_eq(',
    '    "snapshot_values",',
    '    "get_state(config).values refleja el estado actual del hilo",',
    '    snapshot.values["count"],',
    '    [1, 1],',
    ")",
    'check_eq(',
    '    "snapshot_next_empty",',
    '    "get_state(config).next esta vacio cuando el grafo terminó",',
    "    tuple(snapshot.next),",
    "    (),",
    ")",
    "",
    "history = graph.get_state_history(config_a)",
    'check(',
    '    "history_has_entries",',
    '    "get_state_history devuelve al menos un snapshot por invoke del hilo",',
    "    len(list(history)) >= 2,",
    ")",
    "history_list = list(graph.get_state_history(config_a))",
    'check_eq(',
    '    "history_most_recent_first",',
    '    "el snapshot mas reciente aparece primero",',
    '    history_list[0].values["count"],',
    '    [1, 1],',
    ")",
  ].join("\n"),
};

// ---------------------------------------------------------------------------
// 2) HITL: interrupt / Command(resume) — oráculo literal grounding-adv §1
// ---------------------------------------------------------------------------

/** Ejemplo canónico grounding-avanzado §1: debe producir EXACTAMENTE
 *  `{"value": ["Hello, Alice!", "Done"]}` tras el resume (ARCHITECTURE.md
 *  C-RUNNER, fila `Command` — resume). */
export const INTERRUPT_RESUME_CHALLENGE = {
  id: "test-interrupt-resume",
  studentCode: [
    "import operator",
    "from typing import Annotated",
    "from typing_extensions import TypedDict",
    "from langgraph.checkpoint.memory import InMemorySaver",
    "from langgraph.graph import END, START, StateGraph",
    "from langgraph.types import Command, interrupt",
    "",
    "class State(TypedDict):",
    "    value: Annotated[list[str], operator.add]",
    "",
    "def ask_human(state: State):",
    '    answer = interrupt("What is your name?")',
    '    return {"value": [f"Hello, {answer}!"]}',
    "",
    "def final_step(state: State):",
    '    return {"value": ["Done"]}',
    "",
    "graph = (",
    "    StateGraph(State)",
    '    .add_node("ask_human", ask_human)',
    '    .add_node("final_step", final_step)',
    '    .add_edge(START, "ask_human")',
    '    .add_edge("ask_human", "final_step")',
    "    .compile(checkpointer=InMemorySaver())",
    ")",
  ].join("\n"),
  validationCode: [
    "from course_harness import check, check_eq",
    "from langgraph.types import Command",
    "",
    'config = {"configurable": {"thread_id": "1"}}',
    'first = graph.invoke({"value": []}, config)',
    "",
    'check(',
    '    "first_invoke_returns_interrupt",',
    '    "el primer invoke pausa y expone __interrupt__",',
    '    "__interrupt__" in first,',
    "    f\"resultado obtenido: {first!r}\",",
    ")",
    "interrupts = first.get(\"__interrupt__\", [])",
    'check(',
    '    "interrupt_list_nonempty",',
    '    "__interrupt__ trae al menos un objeto de interrupcion",',
    "    len(interrupts) >= 1,",
    ")",
    'check_eq(',
    '    "interrupt_value",',
    '    "el valor del interrupt es el payload pasado a interrupt()",',
    "    interrupts[0].value,",
    '    "What is your name?",',
    ")",
    "",
    'second = graph.invoke(Command(resume="Alice"), config)',
    'check_eq(',
    '    "resume_result",',
    '    "el resume reanuda el nodo interrumpido y produce la salida documentada del grounding-adv §1",',
    "    second,",
    '    {"value": ["Hello, Alice!", "Done"]},',
    ")",
  ].join("\n"),
};

/** `interrupt` sin checkpointer/thread_id ⇒ error claro (ARCHITECTURE.md:
 *  "Requiere checkpointer + thread_id; sin ellos ⇒ error claro en español"). */
export const INTERRUPT_WITHOUT_CHECKPOINTER_CHALLENGE = {
  id: "test-interrupt-without-checkpointer",
  studentCode: [
    "from typing_extensions import TypedDict",
    "from langgraph.graph import END, START, StateGraph",
    "from langgraph.types import interrupt",
    "",
    "class State(TypedDict):",
    "    value: list",
    "",
    "def ask_human(state: State):",
    '    answer = interrupt("What is your name?")',
    '    return {"value": [answer]}',
    "",
    "graph = (",
    "    StateGraph(State)",
    '    .add_node("ask_human", ask_human)',
    '    .add_edge(START, "ask_human")',
    '    .add_edge("ask_human", END)',
    "    .compile()",  // sin checkpointer
    ")",
  ].join("\n"),
  validationCode: [
    "from course_harness import check",
    "",
    'error_message = ""',
    "raised = False",
    "try:",
    '    graph.invoke({"value": []})',
    "except Exception as exc:",
    "    raised = True",
    "    error_message = str(exc)",
    "",
    'check("raises_without_checkpointer", "interrupt sin checkpointer lanza un error", raised)',
    'check(',
    '    "error_mentions_checkpointer_or_thread",',
    '    "el mensaje de error es claro: menciona checkpointer o thread_id",',
    '    ("checkpointer" in error_message.lower()) or ("thread_id" in error_message.lower()),',
    "    f\"mensaje obtenido: {error_message!r}\",",
    ")",
  ].join("\n"),
};

/** `Command(goto=, update=)`: enruta ignorando edges salientes y aplica
 *  `update` con reducers (base de handoffs multi-agente, grounding-adv §4). */
export const COMMAND_GOTO_UPDATE_CHALLENGE = {
  id: "test-command-goto-update",
  studentCode: [
    "import operator",
    "from typing import Annotated",
    "from typing_extensions import TypedDict",
    "from langgraph.graph import END, START, StateGraph",
    "from langgraph.types import Command",
    "",
    "class State(TypedDict):",
    "    log: Annotated[list, operator.add]",
    "",
    "def start_node(state: State):",
    '    return Command(goto="end_node", update={"log": ["from-start"]})',
    "",
    "def end_node(state: State):",
    '    return {"log": ["from-end"]}',
    "",
    "def unreachable_node(state: State):",
    '    return {"log": ["should-not-run"]}',
    "",
    "graph = (",
    "    StateGraph(State)",
    '    .add_node("start_node", start_node)',
    '    .add_node("end_node", end_node)',
    '    .add_node("unreachable_node", unreachable_node)',
    '    .add_edge(START, "start_node")',
    '    .add_edge("start_node", "unreachable_node")',  // Command.goto debe IGNORAR este edge
    '    .add_edge("end_node", END)',
    '    .add_edge("unreachable_node", END)',
    "    .compile()",
    ")",
  ].join("\n"),
  validationCode: [
    "from course_harness import check_eq",
    "",
    'result = graph.invoke({"log": []})',
    'check_eq(',
    '    "command_goto_ignores_edges",',
    '    "Command(goto=) enruta a end_node ignorando el edge declarado hacia unreachable_node",',
    '    result["log"],',
    '    ["from-start", "from-end"],',
    ")",
  ].join("\n"),
};

// ---------------------------------------------------------------------------
// 3) Store: put/search por namespace, determinista; distinción con checkpointer
// ---------------------------------------------------------------------------

export const STORE_PUT_SEARCH_CHALLENGE = {
  id: "test-store-put-search",
  studentCode: [
    "from langgraph.store.memory import InMemoryStore",
    "from langgraph.graph import StateGraph, MessagesState, START, END",
    "",
    "store = InMemoryStore()",
    "",
    "def call_model(state: MessagesState, *, store):",
    '    namespace = ("user-1", "memories")',
    '    store.put(namespace, "pref-1", {"data": "User prefers dark mode"})',
    '    store.put(namespace, "pref-2", {"data": "User prefers concise answers"})',
    '    hits = store.search(namespace, query="dark mode")',
    '    content = "; ".join(h.value["data"] for h in hits)',
    '    return {"messages": [{"role": "ai", "content": content}]}',
    "",
    "builder = StateGraph(MessagesState)",
    "builder.add_node(call_model)",
    'builder.add_edge(START, "call_model")',
    'builder.add_edge("call_model", END)',
    "graph = builder.compile(store=store)",
  ].join("\n"),
  validationCode: [
    "from course_harness import check_eq",
    "",
    'result = graph.invoke({"messages": [{"role": "human", "content": "hola"}]})',
    "last = result[\"messages\"][-1]",
    'check_eq(',
    '    "store_search_filters_by_query",',
    "    \"search(namespace, query=) filtra por coincidencia lexica\",",
    "    last.content,",
    '    "User prefers dark mode",',
    ")",
    "",
    'all_items = store.search(("user-1", "memories"))',
    'check_eq("store_search_all_count", "query=None devuelve todos los items", len(all_items), 2)',
    'check_eq(',
    '    "store_search_all_order",',
    '    "el orden es el de insercion (determinista)",',
    "    [item.key for item in all_items],",
    '    ["pref-1", "pref-2"],',
    ")",
    "",
    'other_namespace_items = store.search(("user-2", "memories"))',
    'check_eq(',
    '    "store_namespace_isolated",',
    '    "un namespace distinto no ve los items de otro",',
    "    other_namespace_items,",
    "    [],",
    ")",
  ].join("\n"),
};

/** Distinción explícita: checkpointer = memoria de UN hilo; Store = memoria
 *  compartida ENTRE hilos (ARCHITECTURE.md, fila InMemoryStore). */
export const STORE_VS_CHECKPOINTER_CHALLENGE = {
  id: "test-store-vs-checkpointer",
  studentCode: [
    "from langgraph.checkpoint.memory import InMemorySaver",
    "from langgraph.store.memory import InMemoryStore",
    "from langgraph.graph import StateGraph, MessagesState, START, END",
    "",
    "shared_store = InMemoryStore()",
    "",
    "def writer(state: MessagesState, *, store):",
    '    store.put(("shared",), "note", {"data": "written by writer"})',
    '    return {"messages": []}',
    "",
    "def reader(state: MessagesState, *, store):",
    '    hits = store.search(("shared",))',
    '    content = hits[0].value["data"] if hits else "none"',
    '    return {"messages": [{"role": "ai", "content": content}]}',
    "",
    "builder_w = StateGraph(MessagesState)",
    'builder_w.add_node("writer", writer)',
    'builder_w.add_edge(START, "writer")',
    'builder_w.add_edge("writer", END)',
    "graph_w = builder_w.compile(checkpointer=InMemorySaver(), store=shared_store)",
    "",
    "builder_r = StateGraph(MessagesState)",
    'builder_r.add_node("reader", reader)',
    'builder_r.add_edge(START, "reader")',
    'builder_r.add_edge("reader", END)',
    "graph_r = builder_r.compile(checkpointer=InMemorySaver(), store=shared_store)",
  ].join("\n"),
  validationCode: [
    "from course_harness import check_eq",
    "",
    'graph_w.invoke({"messages": []}, {"configurable": {"thread_id": "thread-w"}})',
    'result = graph_r.invoke({"messages": []}, {"configurable": {"thread_id": "thread-r"}})',
    "",
    'check_eq(',
    '    "store_shared_across_threads",',
    '    "el Store es memoria compartida ENTRE hilos: un hilo distinto ve lo escrito por otro",',
    '    result["messages"][-1].content,',
    '    "written by writer",',
    ")",
  ].join("\n"),
};

// ---------------------------------------------------------------------------
// 4) Tools: @tool, bind_tools, tool_calls, ToolMessage, ciclo manual + ToolNode
// ---------------------------------------------------------------------------

const MULTIPLY_TOOL_DOUBLES: LlmDoubleLike[] = [
  { respuesta: "", toolCalls: [{ name: "multiply", args: { a: 6, b: 7 } }] },
  { respuesta: "6 times 7 is 42.", toolCalls: [] },
];

/** Ciclo manual modelo→tool→modelo (grounding-adv §3, patrón `should_continue`)
 *  + verificación de determinismo (mismos inputs ⇒ mismos resultados, ids
 *  `call_n` estables por instancia de `FakeChatModel`). */
export const MANUAL_TOOL_CYCLE_CHALLENGE = {
  id: "test-manual-tool-cycle",
  studentCode: [
    "from typing import Literal",
    "from langchain.tools import tool",
    "from langchain.messages import ToolMessage",
    "from langgraph.graph import StateGraph, MessagesState, START, END",
    "from course_harness import FakeChatModel",
    "",
    "@tool",
    "def multiply(a: int, b: int) -> int:",
    '    """Multiply a and b."""',
    "    return a * b",
    "",
    "tools = [multiply]",
    "tools_by_name = {t.name: t for t in tools}",
    "",
    "def build_agent():",
    "    model = FakeChatModel()",
    "    llm_with_tools = model.bind_tools(tools)",
    "",
    "    def llm_call(state: MessagesState):",
    '        return {"messages": [llm_with_tools.invoke(state["messages"])]}',
    "",
    "    def tool_node(state: MessagesState):",
    "        result = []",
    '        for tool_call in state["messages"][-1].tool_calls:',
    '            t = tools_by_name[tool_call["name"]]',
    '            observation = t.invoke(tool_call["args"])',
    '            result.append(ToolMessage(content=str(observation), tool_call_id=tool_call["id"]))',
    '        return {"messages": result}',
    "",
    '    def should_continue(state: MessagesState) -> Literal["tool_node", "__end__"]:',
    '        last = state["messages"][-1]',
    '        return "tool_node" if last.tool_calls else END',
    "",
    "    b = StateGraph(MessagesState)",
    '    b.add_node("llm_call", llm_call)',
    '    b.add_node("tool_node", tool_node)',
    '    b.add_edge(START, "llm_call")',
    '    b.add_conditional_edges("llm_call", should_continue, ["tool_node", END])',
    '    b.add_edge("tool_node", "llm_call")',
    "    return b.compile()",
  ].join("\n"),
  validationCode: [
    "from course_harness import check_eq, get_llm_calls",
    "",
    "agent = build_agent()",
    'result = agent.invoke({"messages": [{"role": "human", "content": "What is 6 times 7?"}]})',
    'messages = result["messages"]',
    "",
    'check_eq(',
    '    "cycle_message_count",',
    '    "el hilo final tiene human + AI(tool_call) + tool + AI(final) = 4 mensajes",',
    "    len(messages),",
    "    4,",
    ")",
    "",
    "ai_with_tool_call = messages[1]",
    'check_eq(',
    '    "tool_call_name",',
    '    "la primera respuesta del modelo llama a multiply",',
    '    ai_with_tool_call.tool_calls[0]["name"],',
    '    "multiply",',
    ")",
    'check_eq(',
    '    "tool_call_args",',
    '    "los argumentos del tool_call son los del double configurado",',
    '    ai_with_tool_call.tool_calls[0]["args"],',
    '    {"a": 6, "b": 7},',
    ")",
    'check_eq(',
    '    "tool_call_id_format",',
    '    "el id del primer tool_call de esta instancia es call_1",',
    '    ai_with_tool_call.tool_calls[0]["id"],',
    '    "call_1",',
    ")",
    "",
    "tool_message = messages[2]",
    'check_eq(',
    '    "tool_message_content",',
    '    "el ToolMessage contiene el resultado de multiply(6, 7)",',
    "    tool_message.content,",
    '    "42",',
    ")",
    'check_eq(',
    '    "tool_message_call_id",',
    '    "el ToolMessage referencia el mismo tool_call_id",',
    "    tool_message.tool_call_id,",
    '    "call_1",',
    ")",
    "",
    "final_ai = messages[3]",
    'check_eq(',
    '    "final_answer",',
    '    "la respuesta final es la del segundo double (sin tool_calls)",',
    "    final_ai.content,",
    '    "6 times 7 is 42.",',
    ")",
    'check_eq("final_no_tool_calls", "la respuesta final no trae tool_calls", final_ai.tool_calls, [])',
    "",
    "calls = get_llm_calls()",
    'check_eq(',
    '    "llm_invoked_twice",',
    '    "el modelo fue invocado 2 veces: una para decidir la tool, otra para la respuesta final",',
    "    len(calls),",
    "    2,",
    ")",
    "",
    "# Determinismo: dos instancias frescas con los mismos inputs producen el mismo resultado",
    "agent_a = build_agent()",
    "agent_b = build_agent()",
    'input_msg = {"messages": [{"role": "human", "content": "What is 6 times 7?"}]}',
    "result_a = agent_a.invoke(input_msg)",
    "result_b = agent_b.invoke(input_msg)",
    'check_eq(',
    '    "determinism_contents",',
    '    "mismos inputs producen los mismos contenidos de mensaje",',
    '    [m.content for m in result_a["messages"]],',
    '    [m.content for m in result_b["messages"]],',
    ")",
    'check_eq(',
    '    "determinism_tool_call_ids",',
    '    "mismos inputs producen los mismos ids call_n (por instancia fresca)",',
    '    result_a["messages"][1].tool_calls[0]["id"],',
    '    result_b["messages"][1].tool_calls[0]["id"],',
    ")",
  ].join("\n"),
  llmDoubles: MULTIPLY_TOOL_DOUBLES,
};

/** `ToolNode` prebuilt: misma semántica que el patrón manual, con menos
 *  código; + "tool inexistente ⇒ error claro". */
export const TOOL_NODE_CHALLENGE = {
  id: "test-tool-node",
  studentCode: [
    "from langchain.tools import tool",
    "from langchain.messages import AIMessage",
    "from langgraph.graph import StateGraph, MessagesState, START, END",
    "from langgraph.prebuilt import ToolNode",
    "from course_harness import FakeChatModel",
    "",
    "@tool",
    "def add(a: int, b: int) -> int:",
    '    """Add a and b."""',
    "    return a + b",
    "",
    "tools = [add]",
    "model = FakeChatModel()",
    "llm_with_tools = model.bind_tools(tools)",
    "",
    "def llm_call(state: MessagesState):",
    '    return {"messages": [llm_with_tools.invoke(state["messages"])]}',
    "",
    "def should_continue(state: MessagesState):",
    '    return "tools" if state["messages"][-1].tool_calls else END',
    "",
    "builder = StateGraph(MessagesState)",
    'builder.add_node("llm_call", llm_call)',
    'builder.add_node("tools", ToolNode(tools))',
    'builder.add_edge(START, "llm_call")',
    'builder.add_conditional_edges("llm_call", should_continue, ["tools", END])',
    'builder.add_edge("tools", "llm_call")',
    "graph = builder.compile()",
  ].join("\n"),
  validationCode: [
    "from course_harness import check_eq, check_raises",
    "from langgraph.prebuilt import ToolNode",
    "from langchain.messages import AIMessage",
    "",
    'result = graph.invoke({"messages": [{"role": "human", "content": "What is 2 plus 3?"}]})',
    'tool_message = result["messages"][2]',
    'check_eq(',
    '    "tool_node_result_content",',
    '    "ToolNode ejecuta la tool y produce un ToolMessage con el resultado",',
    "    tool_message.content,",
    '    "5",',
    ")",
    'check_eq(',
    '    "tool_node_result_call_id",',
    '    "el ToolMessage de ToolNode referencia el tool_call_id correcto",',
    '    tool_message.tool_call_id,',
    '    result["messages"][1].tool_calls[0]["id"],',
    ")",
    "",
    "def invoke_unknown_tool():",
    "    node = ToolNode(tools)",
    '    node({"messages": [AIMessage("", tool_calls=[{"name": "unknown_tool", "args": {}, "id": "call_x"}])]})',
    "",
    'check_raises(',
    '    "tool_node_unknown_tool_raises",',
    '    "ToolNode lanza un error claro si la tool solicitada no existe",',
    "    invoke_unknown_tool,",
    "    Exception,",
    ")",
  ].join("\n"),
  llmDoubles: [
    { respuesta: "", toolCalls: [{ name: "add", args: { a: 2, b: 3 } }] },
    { respuesta: "2 plus 3 is 5.", toolCalls: [] },
  ] as LlmDoubleLike[],
};

// ---------------------------------------------------------------------------
// 5) create_react_agent: loop ReAct determinista con FakeChatModel
// ---------------------------------------------------------------------------

export const CREATE_REACT_AGENT_CHALLENGE = {
  id: "test-create-react-agent",
  studentCode: [
    "from langchain.tools import tool",
    "from langgraph.prebuilt import create_react_agent",
    "from course_harness import FakeChatModel",
    "",
    "@tool",
    "def square(n: int) -> int:",
    '    """Return n squared."""',
    "    return n * n",
    "",
    "tools = [square]",
    "",
    "def build_react_agent():",
    "    model = FakeChatModel()",
    "    return create_react_agent(model, tools)",
  ].join("\n"),
  validationCode: [
    "from course_harness import check_eq",
    "",
    "agent_1 = build_react_agent()",
    "agent_2 = build_react_agent()",
    'input_msg = {"messages": [{"role": "human", "content": "What is 5 squared?"}]}',
    "",
    "result_1 = agent_1.invoke(input_msg)",
    "result_2 = agent_2.invoke(input_msg)",
    "",
    'check_eq(',
    '    "react_final_answer",',
    '    "create_react_agent produce la respuesta final configurada tras el loop ReAct",',
    '    result_1["messages"][-1].content,',
    '    "5 squared is 25.",',
    ")",
    'check_eq(',
    '    "react_deterministic_contents",',
    '    "mismos inputs producen los mismos contenidos de mensaje (dos instancias frescas)",',
    '    [m.content for m in result_1["messages"]],',
    '    [m.content for m in result_2["messages"]],',
    ")",
    "",
    "agent_3 = build_react_agent()",
    'updates = list(agent_3.stream(input_msg, stream_mode="updates"))',
    "node_sequence = [list(u.keys())[0] for u in updates]",
    'check_eq(',
    '    "react_node_sequence",',
    '    "el loop ReAct pasa por los nodos agent -> tools -> agent",',
    "    node_sequence,",
    '    ["agent", "tools", "agent"],',
    ")",
  ].join("\n"),
  llmDoubles: [
    { respuesta: "", toolCalls: [{ name: "square", args: { n: 5 } }] },
    { respuesta: "5 squared is 25.", toolCalls: [] },
  ] as LlmDoubleLike[],
};

// ---------------------------------------------------------------------------
// 6) Streaming stream_mode="messages": tuplas (chunk, metadata) deterministas
// ---------------------------------------------------------------------------

export const STREAM_MESSAGES_CHALLENGE = {
  id: "test-stream-messages",
  studentCode: [
    "from langgraph.graph import StateGraph, MessagesState, START, END",
    "from course_harness import FakeChatModel",
    "",
    "model = FakeChatModel()",
    "",
    "def call_model(state: MessagesState):",
    '    return {"messages": [model.invoke(state["messages"])]}',
    "",
    "builder = StateGraph(MessagesState)",
    'builder.add_node("call_model", call_model)',
    'builder.add_edge(START, "call_model")',
    'builder.add_edge("call_model", END)',
    "graph = builder.compile()",
  ].join("\n"),
  validationCode: [
    "from course_harness import check, check_eq",
    "",
    'input_msg = {"messages": [{"role": "human", "content": "hi"}]}',
    'chunks = list(graph.stream(input_msg, stream_mode="messages"))',
    "",
    'check("messages_stream_nonempty", "stream_mode=\'messages\' produce al menos un chunk", len(chunks) > 0)',
    'check(',
    '    "messages_stream_shape",',
    '    "cada elemento del stream es una tupla (chunk, metadata)",',
    "    all(isinstance(item, tuple) and len(item) == 2 for item in chunks),",
    ")",
    'check(',
    '    "messages_stream_metadata_node",',
    '    "metadata incluye langgraph_node == call_model para todos los chunks",',
    '    all(item[1].get("langgraph_node") == "call_model" for item in chunks),',
    ")",
    "",
    "texts = [item[0].content for item in chunks]",
    'reconstructed = "".join(texts)',
    'check_eq(',
    '    "messages_stream_reconstructs_full_message",',
    '    "concatenar los chunks reconstruye el mensaje completo del double",',
    "    reconstructed,",
    '    "Hello world from LangGraph",',
    ")",
    "",
    'chunks_2 = list(graph.stream(input_msg, stream_mode="messages"))',
    "texts_2 = [item[0].content for item in chunks_2]",
    'check_eq(',
    '    "messages_stream_deterministic",',
    '    "el mismo input produce el mismo troceo de chunks (determinista por palabras)",',
    "    texts,",
    "    texts_2,",
    ")",
  ].join("\n"),
  llmDoubles: [{ respuesta: "Hello world from LangGraph" }] as LlmDoubleLike[],
};

// ---------------------------------------------------------------------------
// 7) Superstep atómico (ADR-08): fan-out con reducer + InvalidUpdateError
// ---------------------------------------------------------------------------

/** Dos nodos del mismo superstep escriben una clave CON reducer: se aplican
 *  ambos, en orden determinista de registro (`add_node`). */
export const FANOUT_WITH_REDUCER_CHALLENGE = {
  id: "test-fanout-with-reducer",
  studentCode: [
    "import operator",
    "from typing import Annotated",
    "from typing_extensions import TypedDict",
    "from langgraph.graph import StateGraph, START, END",
    "",
    "class State(TypedDict):",
    "    values: Annotated[list, operator.add]",
    "",
    "def node_a(state: State):",
    '    return {"values": ["a"]}',
    "",
    "def node_b(state: State):",
    '    return {"values": ["b"]}',
    "",
    "builder = StateGraph(State)",
    'builder.add_node("node_a", node_a)',
    'builder.add_node("node_b", node_b)',
    'builder.add_edge(START, "node_a")',
    'builder.add_edge(START, "node_b")',
    'builder.add_edge("node_a", END)',
    'builder.add_edge("node_b", END)',
    "graph = builder.compile()",
  ].join("\n"),
  validationCode: [
    "from course_harness import check_eq",
    "",
    'result = graph.invoke({"values": []})',
    'check_eq(',
    '    "fanout_reducer_deterministic_order",',
    '    "el reducer aplica las escrituras del superstep en orden de registro (add_node): a antes que b",',
    '    result["values"],',
    '    ["a", "b"],',
    ")",
  ].join("\n"),
};

/** Invariante clave del superstep atómico: los nodos hermanos leen el estado
 *  PREVIO al superstep, nunca las escrituras de sus hermanos. */
export const SUPERSTEP_SIBLINGS_READ_PRIOR_STATE_CHALLENGE = {
  id: "test-superstep-siblings-prior-state",
  studentCode: [
    "import operator",
    "from typing import Annotated",
    "from typing_extensions import TypedDict",
    "from langgraph.graph import StateGraph, START, END",
    "",
    "class State(TypedDict):",
    "    items: Annotated[list, operator.add]",
    "",
    "def seed(state: State):",
    '    return {"items": ["seed"]}',
    "",
    "def sibling_a(state: State):",
    '    return {"items": [f"a-saw-{len(state[\'items\'])}"]}',
    "",
    "def sibling_b(state: State):",
    '    return {"items": [f"b-saw-{len(state[\'items\'])}"]}',
    "",
    "builder = StateGraph(State)",
    'builder.add_node("seed", seed)',
    'builder.add_node("sibling_a", sibling_a)',
    'builder.add_node("sibling_b", sibling_b)',
    'builder.add_edge(START, "seed")',
    'builder.add_edge("seed", "sibling_a")',
    'builder.add_edge("seed", "sibling_b")',
    'builder.add_edge("sibling_a", END)',
    'builder.add_edge("sibling_b", END)',
    "graph = builder.compile()",
  ].join("\n"),
  validationCode: [
    "from course_harness import check_eq",
    "",
    'result = graph.invoke({"items": []})',
    "# Tras `seed` (superstep 1), items = ['seed'] (len 1). sibling_a y sibling_b",
    "# corren en el MISMO superstep (2): si vieran el estado del cierre del",
    "# superstep anterior (invariante correcto), AMBOS observan len == 1. Si en",
    "# cambio uno viera la escritura ya aplicada del otro (bug de merge inmediato",
    "# en vez de supersteps atomicos), uno de los dos observaria len == 2.",
    'check_eq(',
    '    "siblings_see_prior_state_not_each_others_write",',
    '    "ambos nodos del mismo superstep ven el estado previo, no la escritura del hermano",',
    "    sorted(result[\"items\"]),",
    '    ["a-saw-1", "b-saw-1", "seed"],',
    ")",
  ].join("\n"),
};

/** Escritura concurrente a una clave SIN reducer en el mismo superstep debe
 *  lanzar `InvalidUpdateError` (ARCHITECTURE.md §superstep, ADR-08).
 *
 * ASUNCIÓN DE CONTRATO: la tabla del shim fija el NOMBRE de la excepción
 * (`InvalidUpdateError`) pero no el path de import literal. Se asume
 * `langgraph.errors.InvalidUpdateError` (path real de LangGraph, coherente
 * con "igual que LangGraph real" en ARCHITECTURE.md). Si el implementer usa
 * otro módulo, es un desvío de contrato a ratificar por el architect. */
export const CONCURRENT_WRITE_NO_REDUCER_CHALLENGE = {
  id: "test-concurrent-write-no-reducer",
  studentCode: [
    "from typing_extensions import TypedDict",
    "from langgraph.graph import StateGraph, START, END",
    "",
    "class State(TypedDict):",
    "    value: str",
    "",
    "def writer_x(state: State):",
    '    return {"value": "x"}',
    "",
    "def writer_y(state: State):",
    '    return {"value": "y"}',
    "",
    "builder = StateGraph(State)",
    'builder.add_node("writer_x", writer_x)',
    'builder.add_node("writer_y", writer_y)',
    'builder.add_edge(START, "writer_x")',
    'builder.add_edge(START, "writer_y")',
    'builder.add_edge("writer_x", END)',
    'builder.add_edge("writer_y", END)',
    "graph = builder.compile()",
  ].join("\n"),
  validationCode: [
    "from course_harness import check_raises",
    "from langgraph.errors import InvalidUpdateError",
    "",
    "def run_conflict():",
    '    graph.invoke({"value": ""})',
    "",
    'check_raises(',
    '    "concurrent_write_no_reducer_raises",',
    '    "escritura concurrente a clave sin reducer en el mismo superstep lanza InvalidUpdateError",',
    "    run_conflict,",
    "    InvalidUpdateError,",
    ")",
  ].join("\n"),
};
